<a href="https://colab.research.google.com/github/kbd95/NLP/blob/master/Learn_embedd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Learning an Embedding**

In [21]:
from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import Embedding
from tensorflow.keras.preprocessing.text import one_hot

In [22]:
#define document
docs = ["Well done",
        "Good work",
        "Great effort",
        "nice work",
        "Excellent",
        "Weak",
        "poor effort",
        "not good",
        "poor work",
        "Could have done better."]
#define class labels
label = array([1,1,1,1,1,0,0,0,0,0])        

In [23]:
#integer encode the document
vocab_size = 50
encoded_docs = [one_hot(d,vocab_size) for d in docs]
print(encoded_docs)

[[38, 31], [39, 45], [8, 43], [17, 45], [40], [41], [12, 43], [15, 39], [12, 45], [16, 8, 31, 14]]


In [24]:
# pad documents to a max length of 4 words
max_length =4
padded_docs = pad_sequences(encoded_docs,maxlen=max_length,padding="post")
print(padded_docs)

[[38 31  0  0]
 [39 45  0  0]
 [ 8 43  0  0]
 [17 45  0  0]
 [40  0  0  0]
 [41  0  0  0]
 [12 43  0  0]
 [15 39  0  0]
 [12 45  0  0]
 [16  8 31 14]]


In [25]:
#define the model
model = Sequential()
model.add(Embedding(vocab_size,8,input_length=max_length))
model.add(Flatten())

model.add(Dense(1,activation="sigmoid"))

#compile the model
model.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])
#summarize the model
print(model.summary)


<bound method Network.summary of <keras.engine.sequential.Sequential object at 0x7fc303961a90>>


In [26]:
#fit the model
model.fit(padded_docs,label,epochs=50,verbose=0)

#evaluate the model
loss,accuracy = model.evaluate(padded_docs,label,verbose=0)
print("Accuracy: %f" % (accuracy*100))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/indexed_slices.py:434: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Accuracy: 80.000001
